- scripts/check_urls.py
- scripts/uploadChanges.py
- tables_en/1-01-01.csv
update scripts and minor csv cleanup
> Script test2

- tables_en/1-01-01.csv
- tables_en/superseded.csv
- wmdr/ObservedVariableAtmosphere/12249.ttl
- wmdr/ObservedVariableAtmosphere/12250.ttl
- wmdr/ObservedVariableAtmosphere/251.ttl
> merge issue381 into FT branch

- tables_en/1-02.csv
- wmdr/unit/mS.cm-1.ttl
> Merge Issue396 into FT2022-2

- tables_en/2-02.csv
- tables_en/superseded.csv
- wmdr/ProgramAffiliation/ANTONs.ttl
- wmdr/ProgramAffiliation/ANTONt.ttl
> merge issue385new into FT2022-2

- tables_en/1-02.csv
- wmdr/unit/mS.cm-1.ttl
> Issue396 merge into FT2022-2

- tables_en/1-01-01.csv
> remove notation 37, #416

- tables_en/5-02-03.csv
> 422 new table 5 02 03 measurementobserving method ocean

- tables_en/2-02.csv
> add GSRN #424

- tables_en/1-02.csv
- wmdr/unit/fmol.kg-1.ttl
- wmdr/unit/nmol.kg-1.ttl
- wmdr/unit/permeg.ttl
- wmdr/unit/pmol.kg-1.ttl
> issue #454, add codes to new branch

- tables_en/1-01-01.csv
- tables_en/deprecated.csv
issue #417 will not move forward pending discussions on implementation; issue #507 will be changed
> reverse wind updates

- .gitignore
- scripts/README.md
- scripts/requirements_deployment.txt
- scripts/synchroniseTestProd.py
Synchronise all Prod content to Test, not just the registers that already exist:
> Synchronise all Prod registers to Test instance

- tables_en/superseded.csv
> issue Bug: Superseded unit in WMDR code table #520

- .github/ISSUE_TEMPLATE/amendment-proposal.yml
add text area for data exchange plans and other cleanup
> Update issue template

- scripts/requirements_deployment.txt
- tables_en/1-01-03.csv
- wmdr/ObservedVariableOcean/iss596.ttl
> 596 snow depth

- tables_en/2-02.csv
- tables_en/deprecated.csv
- wmdr/ProgramAffiliation/GAWnonAffiliated.ttl
> 585 remove gaw nonaffiliated

- tables_en/1-01-03.csv
- wmdr/ObservedVariableOcean/402.ttl
> #571 update branch

- tables_en/1-02.csv
- wmdr/unit/V2.m-2.Hz-1.ttl
- wmdr/unit/nT2.Hz-1.ttl
- wmdr/unit/pT2.Hz-1.ttl
> 554 add unit

- tables_en/1-01-03.csv
- wmdr/ObservedVariableOcean/iss560.ttl
> update branch for issue #560

- tables_en/1-01-03.csv
- wmdr/ObservedVariableOcean/12325.ttl
- wmdr/ObservedVariableOcean/iss564.ttl
> 564 surface stokes drift

- tables_en/1-01-05.csv
- wmdr/ObservedVariableTerrestrial/725.ttl
- wmdr/ObservedVariableTerrestrial/726.ttl
> Revert "584 lake river ice thickness"

- tables_en/1-01-03.csv
- wmdr/ObservedVariableOcean/iss586.ttl
> Revert "Table 1-01-03 add sea ice variable: Sea-ice stage of development #586…"
